import os

import frappe
from frappe.model.document import Document

_FONT_MAP = {
	"Inter": "'Inter', sans-serif",
	"Arial": "Arial, sans-serif",
	"Helvetica": "Helvetica, Arial, sans-serif",
	"Georgia": "Georgia, serif",
	"Verdana": "Verdana, sans-serif",
	"Tahoma": "Tahoma, sans-serif",
	"System Default": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
}


class DisplaySettings(Document):
	def on_update(self):
		_write_theme_css(self)


def _write_theme_css(doc):
	font_stack = _FONT_MAP.get(doc.font_family or "Inter", "'Inter', sans-serif")
	font_size = doc.font_size or "13px"
	text_color = doc.text_color or "#333333"
	muted_color = doc.muted_text_color or "#555555"

	css = (
		"/* Auto-generated by Display Settings — panels only */\n"
		".panel-float,\n"
		".panel-float .panel-table td,\n"
		".panel-float .panel-table th,\n"
		".panel-float .pane-label,\n"
		".panel-float .pane-count,\n"
		".panel-float .drill-btn,\n"
		".panel-float .panel-float-footer,\n"
		".panel-float .pane-filter-widget,\n"
		".panel-float .pane-core-filter-widget,\n"
		".panel-float .filter-col-select,\n"
		".panel-float .filter-op-select,\n"
		".panel-float .filter-val-input,\n"
		".panel-float .core-filter-input {\n"
		f"  font-family: {font_stack};\n"
		f"  font-size: {font_size};\n"
		"}\n\n"
		".panel-float .panel-table td {\n"
		f"  color: {text_color};\n"
		"}\n\n"
		".panel-float .panel-table th,\n"
		".panel-float .pane-count,\n"
		".panel-float .drill-btn.disabled {\n"
		f"  color: {muted_color};\n"
		"}\n"
	)

	# Write to app source (survives bench build)
	source_path = frappe.get_app_path("nce_events", "public", "css", "custom_theme.css")
	os.makedirs(os.path.dirname(source_path), exist_ok=True)
	with open(source_path, "w") as f:
		f.write(css)

	# Write to served assets (takes effect immediately without bench build)
	served_path = os.path.join(
		frappe.local.sites_path, "assets", "nce_events", "css", "custom_theme.css"
	)
	os.makedirs(os.path.dirname(served_path), exist_ok=True)
	with open(served_path, "w") as f:
		f.write(css)

	frappe.msgprint(
		f"Theme CSS updated — font: {doc.font_family}, size: {font_size}. Hard-refresh to see changes.",
		indicator="green",
		alert=True,
	)
